app:
  # local | dev | prod
  env: local
  datacenterID: 0
  workerID: -1
  workerPrefix: /sakura/worker
  lastTimePrefix: /sakura/last-time

log:
  level: debug
  path: logs
  # megabytes
  maxSize: 50
  # days
  maxAge: 7
  compress: true

grpc:
  ip:
  port: 50051

etcd:
  endpoints:
    - 127.0.0.1:12379
    - 127.0.0.1:22379
    - 127.0.0.1:32379
  timeout: 5
  username:
  password:
  servicePrefix: /sakura/service
  serviceLeaseTTL: 12
