// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.0
// source: pb/sakura.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_sakura_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_sakura_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_pb_sakura_proto_rawDescGZIP(), []int{0}
}

type GenerateReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GenerateReply) Reset() {
	*x = GenerateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_sakura_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReply) ProtoMessage() {}

func (x *GenerateReply) ProtoReflect() protoreflect.Message {
	mi := &file_pb_sakura_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReply.ProtoReflect.Descriptor instead.
func (*GenerateReply) Descriptor() ([]byte, []int) {
	return file_pb_sakura_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GenerateMultiRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int64 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *GenerateMultiRequest) Reset() {
	*x = GenerateMultiRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_sakura_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateMultiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateMultiRequest) ProtoMessage() {}

func (x *GenerateMultiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_sakura_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateMultiRequest.ProtoReflect.Descriptor instead.
func (*GenerateMultiRequest) Descriptor() ([]byte, []int) {
	return file_pb_sakura_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateMultiRequest) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

type GenerateMultiReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []int64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *GenerateMultiReply) Reset() {
	*x = GenerateMultiReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_sakura_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateMultiReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateMultiReply) ProtoMessage() {}

func (x *GenerateMultiReply) ProtoReflect() protoreflect.Message {
	mi := &file_pb_sakura_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateMultiReply.ProtoReflect.Descriptor instead.
func (*GenerateMultiReply) Descriptor() ([]byte, []int) {
	return file_pb_sakura_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateMultiReply) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_pb_sakura_proto protoreflect.FileDescriptor

var file_pb_sakura_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x62, 0x2f, 0x73, 0x61, 0x6b, 0x75, 0x72, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x73, 0x61, 0x6b, 0x75, 0x72, 0x61, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1f, 0x0a, 0x0d,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2e, 0x0a,
	0x14, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x26, 0x0a,
	0x12, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03,
	0x52, 0x03, 0x69, 0x64, 0x73, 0x32, 0x96, 0x01, 0x0a, 0x09, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x12, 0x3c, 0x0a, 0x08, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x12,
	0x17, 0x2e, 0x73, 0x61, 0x6b, 0x75, 0x72, 0x61, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x73, 0x61, 0x6b, 0x75, 0x72,
	0x61, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x12, 0x4b, 0x0a, 0x0d, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4d, 0x75, 0x6c,
	0x74, 0x69, 0x12, 0x1c, 0x2e, 0x73, 0x61, 0x6b, 0x75, 0x72, 0x61, 0x2e, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x73, 0x61, 0x6b, 0x75, 0x72, 0x61, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x1f,
	0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x68, 0x6f,
	0x6f, 0x6b, 0x65, 0x74, 0x68, 0x2f, 0x73, 0x61, 0x6b, 0x75, 0x72, 0x61, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_sakura_proto_rawDescOnce sync.Once
	file_pb_sakura_proto_rawDescData = file_pb_sakura_proto_rawDesc
)

func file_pb_sakura_proto_rawDescGZIP() []byte {
	file_pb_sakura_proto_rawDescOnce.Do(func() {
		file_pb_sakura_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_sakura_proto_rawDescData)
	})
	return file_pb_sakura_proto_rawDescData
}

var file_pb_sakura_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pb_sakura_proto_goTypes = []interface{}{
	(*GenerateRequest)(nil),      // 0: sakura.GenerateRequest
	(*GenerateReply)(nil),        // 1: sakura.GenerateReply
	(*GenerateMultiRequest)(nil), // 2: sakura.GenerateMultiRequest
	(*GenerateMultiReply)(nil),   // 3: sakura.GenerateMultiReply
}
var file_pb_sakura_proto_depIdxs = []int32{
	0, // 0: sakura.Generator.Generate:input_type -> sakura.GenerateRequest
	2, // 1: sakura.Generator.GenerateMulti:input_type -> sakura.GenerateMultiRequest
	1, // 2: sakura.Generator.Generate:output_type -> sakura.GenerateReply
	3, // 3: sakura.Generator.GenerateMulti:output_type -> sakura.GenerateMultiReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_sakura_proto_init() }
func file_pb_sakura_proto_init() {
	if File_pb_sakura_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_sakura_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_sakura_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_sakura_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateMultiRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_sakura_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateMultiReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_sakura_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_sakura_proto_goTypes,
		DependencyIndexes: file_pb_sakura_proto_depIdxs,
		MessageInfos:      file_pb_sakura_proto_msgTypes,
	}.Build()
	File_pb_sakura_proto = out.File
	file_pb_sakura_proto_rawDesc = nil
	file_pb_sakura_proto_goTypes = nil
	file_pb_sakura_proto_depIdxs = nil
}
